// ============================================================================
// Trip-GUY — Travel Super-App
// Copyright (c) 2026 Gnanasekaran D. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This source code and all associated files are the exclusive intellectual
// property of Gnanasekaran D. Unauthorized copying, modification, distribution,
// or use of this file, via any medium, is strictly prohibited.
//
// Contact : sgnana238@gmail.com | +91 8248094569
// Country : India
// License : See LICENSE file at the project root for full terms.
// ============================================================================
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHbliFQLZsB2oKUivyMOuGki8lDfFp_w',
    appId: '1:542606850425:android:4e27a2ac59b94cf7db17a8',
    messagingSenderId: '542606850425',
    projectId: 'trip-guy-8292f',
    databaseURL: 'https://trip-guy-8292f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-guy-8292f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FC60nxIpTzwO0C0aAVHRZfoLceTwJYg',
    appId: '1:542606850425:ios:f3c9c152631e6603db17a8',
    messagingSenderId: '542606850425',
    projectId: 'trip-guy-8292f',
    databaseURL: 'https://trip-guy-8292f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-guy-8292f.firebasestorage.app',
    iosBundleId: 'com.tripguy.tripGuy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8t0MQ1Aiad-3v_hwFQhZ5s5Ry9epy_Y',
    appId: '1:542606850425:web:756166372e5a2c05db17a8',
    messagingSenderId: '542606850425',
    projectId: 'trip-guy-8292f',
    authDomain: 'trip-guy-8292f.firebaseapp.com',
    databaseURL: 'https://trip-guy-8292f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-guy-8292f.firebasestorage.app',
  );

}